### ISSUE TITLE
Better error formatting

### ISSUE THREAD

**Issue by coryodaniel** [coryodaniel/k8s#100]
Better error formatting

`{:error, {:not_found, {'namespace does not exist', 'default'}}}`

**Comment by fridayy** [comment]
Hi @coryodaniel, first of all thanks for this great lib it already served me well in a personal project. I'd love to contribute and help if I may (I'm no elixir expert tho).

I played around a bit with the response handling part in `K8s.Client.HTTPProvider`:

```elixir 
  def handle_response(resp) do
    case resp do
      {:ok, %HTTPoison.AsyncResponse{id: ref}} ->
        {:ok, ref}

      {:ok, %HTTPoison.Response{status_code: code, body: body, headers: headers}}
      when code in 200..299 ->
        content_type = get_content_type(headers)
        {:ok, decode(body, content_type)}

      {:ok, %HTTPoison.Response{status_code: code} = err}
      when code in 400..599 ->
        handle_error(err)

      {:error, %HTTPoison.Error{} = err} ->
        {:error, err}
    end
  end

  defp handle_error(%HTTPoison.Response{status_code: _code, body: body, headers: headers} = resp) do
    content_type = get_content_type(headers)
    # use the content type to check the 'origin' of the error
    case get_content_type(headers) do
      {_, "application/json"} ->
        decode(body, content_type)
        |> handle_kubernetes_error()

      _other ->
        # 'non' k8s errors like standard 404 responses should be more the exception than the rule, right?
        {:error, resp}
    end
  end

  # Kubernetes specific errors are typically wrapped in a JSON body
  # see: https://github.com/kubernetes/apimachinery/blob/master/pkg/api/errors/errors.go
  # so one must differentiate between e.g ordinary 404s and kubernetes 404
  defp handle_kubernetes_error(%{"reason" => reason, "message" => message}),
    do: {:error, {reason, message}}
```

I think one must differentiate between error responses produced by the k8s API and 'ordinary' http errors. The latter being more the exception than the rule but might happen in cases like this:
`iex(23)> K8s.Client.get("core/", "Pod", name: "xxx") |> K8s.Client.run(conn)`
where the user entered a malformed API version (which probably should be handled in `operation.ex`).

Whereas errors from the Kubernetes API contain a JSON body with more or less useful information that could be propagated directly to the user as the following term: `{:error, {Reason, Message}}`
Reason would be a string and not an atom but I don't think it would be worth the effort (and atoms) converting the reason to an atom representation. Same goes for custom messages instead for the ones the API already provides. What do you think?

```
iex(26)> K8s.Client.get("v1", "Namespace", name: "xyz") |> K8s.Client.run(conn)
{:error, {"NotFound", "namespaces \"xyz\" not found"}}
```
However I think the error response term should be harmonized and use a common format in all possible cases.

Please let me know you could use my help or if I am completely off track here.

Thanks in advance and sorry for the wall of text (in bad english).

Cheers

**Comment by coryodaniel** [comment]
Just getting around to this 😓!

this is good feedback!

I think there are two or three classes of errors:
- invalid operations (could probably use some validation logic on operations)
- kubernetes  4xx/5xx
- k8s.ex internals (not sure if there would be any w good validation)

I was planning to define an error module for each class of error w a struct w details so all error signatures would be {:error, StructOfSomeSortYouCanMatchOn}.
