### ISSUE TITLE
K8s.Client.create - support generateName ?

### ISSUE THREAD

**Issue by darrenclark** [coryodaniel/k8s#102]
It'd be nice if `K8s.Client.create/1` supported [`generateName`](https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values).  In particular, I'm using `k8s` for creating jobs, i.e.:

```elixir
operation =
  %{
    "apiVersion" => "batch/v1",
    "kind" => "Job",
    "metadata" => %{
      "generateName" => "my-job-",
      "namespace" => "my-namespace"
    },
    "spec" => # ...
  }
  |> K8s.Client.create()
```

[The pattern matching here prevents this from working](https://github.com/coryodaniel/k8s/blob/cfa6c953aa7fbe6cb328acd0c576b79636007dc7/lib/k8s/client.ex#L261-L277)

I've got a workaround for now (creating the operation via `%K8s.Operation{...}`), but I'd be happy to submit a patch for `K8s.Client.create/1` - thoughts?

**Comment by coryodaniel** [comment]
I’d say that’s a bug! I can cut a release this weekend if you can send over a PR.
