### ISSUE TITLE
What is a good way to watch a resource?

### ISSUE THREAD

**Issue by ebengt** [coryodaniel/k8s#152]
Greetings,

I have K8s 1.1.4.
Erlang/OTP 24 [erts-12.3]
Interactive Elixir (1.12.3)
After the problems described in (https://github.com/coryodaniel/k8s/issues/145) I switched to watch_and_stream/1. It works, but I am probably doing it wrong.

gen_server init/1 code:
```
	{ok, Connection} = 'Elixir.K8s.Conn':from_service_account(),
	List = 'Elixir.K8s.Client':list(<<"v1">>, configmap, [{namespace, N}]),
	{ok, Stream} = 'Elixir.K8s.Client':watch_and_stream(Connection, List, [{recv_timeout, Interval}]),
	F = fun ?MODULE:response/1,
	Pid = erlang:spawn_link( fun() -> 'Elixir.Stream':run( 'Elixir.Stream':map(Stream, F) ) end ),
	State#{stream_pid => Pid};
```
?MODULE:response will cast the response to the gen_server that does the right thing.
This works, but once every hour the linked process terminate. My gen_server is not expecting {'EXIT',Pid,normal}, and crash.
The supervisor restart it all so no loss of functionality.

Is this a sensible way to use watch_and_stream/1 ?
Is there a way to avoid Stream.run/1 returning after 1 hour?

**Comment by mruoss** [comment]
The way I'm using `K8s.Client.watch_and_stream` in bonny is by adding it to the supervisor tree. Have a look at the following files (hope this helps):

* [`Bonny.Server.AsyncStreamRunner`](https://github.com/coryodaniel/bonny/blob/master/lib/bonny/server/async_stream_runner.ex)
* Where I use it: https://github.com/coryodaniel/bonny/blob/master/lib/bonny/controller.ex#L59

I'm actually running this code in production.

**Comment by ebengt** [comment]
Thank you.
This means  watch_and_stream/1 is supposed to end and Stream.run/1 will return.
Can I find out more about when/how this ending is supposed to take place?

**Comment by mruoss** [comment]
In theory it's not supposed to end. However, if k8s sends something the stream resource can't deal with, there's nothing it can do so it ends the stream.

Lookout for `{:halt, nil}` in
https://github.com/coryodaniel/k8s/blob/develop/lib/k8s/client/runner/watch/stream.ex

I don't know what leads to the stream ending in your case, though.

**Comment by ebengt** [comment]
My gen_server is now expecting {'EXIT',Pid,normal} when Stream.run/1 returns.
It seems to work.
