### ISSUE TITLE
Question: Is there an example of Client.patch/4 available?

### ISSUE THREAD

**Issue by ebengt** [coryodaniel/k8s#166]
Greetings,
I have a custom resource that I can do get/3 with.
I am trying to do patch/2, and get {:ok, %{}} back.
The custom resource does not change.

Should custom resource change when I use patch/4?
What should I put in the the subresource map?
Currently I have random:  %{"kalle" => 123}

**Comment by mruoss** [comment]
Hey, there is now also [`Client.apply/2`](https://hexdocs.pm/k8s/K8s.Client.html#apply/2) since 1.1.0. I think it is the most suitable function in most cases and probably does what you want.
If you want to use patch, get familiar with the kubernetes patch operation.

**Comment by ebengt** [comment]
Thank you very much for the prompt answer.

The suggested alternative, Client.apply/2, has the option: fieldManager: "my-operator"
Does that mean I need an operator before using  Client.apply/2?

The subresourcemap is the whole resource map, plus my addition? Is that always so? Or only for  Client.apply/2

**Comment by mruoss** [comment]
> The suggested alternative, Client.apply/2, has the option: fieldManager: "my-operator" Does that mean I need an operator before using Client.apply/2?

No you don't. You can pass any binary or just ommit the options. The fieldManager will default to "Elixir". Refer to the Kubernetes documentation for server-side apply if you want to understand the concept.

> The subresourcemap is the whole resource map, plus my addition? Is that always so? Or only for Client.apply/2

Do you want to change a subresource? Or just the resource? If you want to change the resource, just pass the altered resource to `Client.apply/1`

**Comment by ebengt** [comment]
When fieldManager: is optional, the best method to change my custom resource seems to be Client.apply/2. I will concentrate on that.

My custom resource, cr, has several keys. My plan is to put something(*) into it. End result: Map.put(cr, "status" %{"message" => "some message"})
In my mind I am changing a subresource, since it is a part of the resource. But Kubernetes/K8s might mean something else with subresource. And I am actually changing the resource.
I do
```
    {:ok, cr} = K8s.Client.run(connection, get)
   crstatus = cr |> Map.delete("metadata") |> Map.put("status", %{"message" => "some message"})
    apply = K8s.Client.apply(api, "Config", [namespace: "dev", name: "config-sample"], crstatus, force: :true)
    {:ok, _} = K8s.Client.run(connection, apply)

``` 
cr has not changed after that.
I do K8s.Client.run(connection, get) again and see no %{"status => ...}

(*) Something is copied from the K8s documentation to simplify.

**Comment by mruoss** [comment]
Please use code formatting in your messages, thanks.

Not any field is a subresource, but `status` actually is (see https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#subresources). This means you have to patch the subresource using  [`Client.apply/5`](https://hexdocs.pm/k8s/K8s.Client.html#apply/5). I think you have to use the plural version of your resource name and append `/status` to the kind. Have a look at the example on hexdocs. You have to send the full resource (without resourceVersion and such), not just the status map as the 4th parameter. So if I understand your code correctly, the only thing you need to change, ist the kind (should be something like "configs/status"). Also your CRD should define the fields inside the status subresource. Not sure though you can just delete the entire metadata. You might have to keep name and namespace.

**Comment by ebengt** [comment]
Thank you very much. I have updated with code formatting.
I will try your kind suggestions.

Only changing kind to `Configs/status` adds an empty status to the custom resource.
Next I will add `message` to status in CRD.

Follow-up question to status as subresource. There is 
```
    Subresources:
      Status:
```
But there is also another status
```
    Schema:
      openAPIV3Schema:
        Properties:
          Kind:
          API Version:
...
          Status:
            Description:  ConfigStatus defines the observed state of Config
            Type:         object
```
If I change this other status, then I am not changing a subresource. Correct?
Should I still use Client.apply/5 ?
How should `crstatus` look then?

After adding "message" as a string to `subresource.status` in CRD, I ran the sample code again. This time I see a change. It does not matter if `kind` is "Configs/status" or "Config".

```
"managedFields" => [
       %{
         "apiVersion" => "config.travelping.net/v1",
         "fieldsType" => "FieldsV1",
         "fieldsV1" => %{
           "f:spec" => %{
             "f:MAX" => %{},
             "f:AFTER" => %{}
           },
           "f:status" => %{"f:message" => %{}}
         },
         "manager" => "elixir",
         "operation" => "Apply",
         "time" => "2022-07-08T11:04:21Z"
}
```
Only managedFields change, no change to what I `get`.

To only `get` status I changed `kind` to "Configs/status", but I get the same result as for kind "Config". Could it be that the two `status` are the same?

**Comment by mruoss** [comment]
Please refer to the kubernetes documentation for these kind of questions. You should find your answers there.

**Comment by ebengt** [comment]
I could not understand the Kubernetes documentation (ie it does not mention the second status).
But it is not a K8s question.
The original K8s question is responded properly.
I will use Client.apply/5, with kind set to custom resource plural + /status for patching and full resource as 4:th argument.
