### ISSUE TITLE
Source links in the documentation are incorrect

### ISSUE THREAD

**Issue by icehaunter** [coryodaniel/k8s#172]
On https://hexdocs.pm/k8s/ all the links to function/module source code look like they've been incorrectly generated, e.g. in the https://hexdocs.pm/k8s/K8s.Client.html the link to the module reads `https://github.com/coryodaniel/k8s/blob/1.1.5//Users/mruoss/src/ufg/community/k8s/lib/k8s/client.ex#L1` when it should `https://github.com/coryodaniel/k8s/blob/1.1.5/k8s/lib/k8s/client.ex#L1`

I believe this is a generator misconfiguration, as these look like absolute paths on the @mruoss machine :)

**Comment by mruoss** [comment]
Yes! I have noticed some time ago and was like _I need to fix this ASAP_. But I have been a bit short on _P_ so I forgot. If anybody knows what's wrong, please let me know, otherwise I am gonna investigate ASAP!

**Comment by icehaunter** [comment]
Checked out code and ran `mix deps.get && mix docs` -- it generated correct links. No idea how they could've been generated incorrectly in the first place, I cannot find a relevant setting at all. 

My machine is on Arch Linux tho, not on MacOS (judging by the path format)

**Comment by mruoss** [comment]
Tried it again on my MacOS - no luck. So I used my Linux machine to republish the docs. Should be fixed now. 

I'd still be intersted to know why that did not work on MacOS but don't have the time to investigate further right now...
