### ISSUE TITLE
Broken links in Readme / Hexdocs

### ISSUE THREAD

**Issue by Rodeoclash** [coryodaniel/k8s#18]
First off, awesome library. I've been digging into it the past couple of hours and I've really enjoyed it. I'll be tearing out the jury rigged K8s API that I've made and replacing it with this.

A small note, the links to the Certificate and Token example files are broken in the readme + hex docs. I should be able to put together a PR to fix in the next few days if you'd like.

**Comment by coryodaniel** [comment]
Thanks! Let me know if you have any questions!
