### ISSUE TITLE
2.0.0-rc.1 doesn't work with kind clusters

### ISSUE THREAD

**Issue by elliottneilclark** [coryodaniel/k8s#203]
I use kind locally for development. When testing 2.0.0-rc.1 I get the following error:
```
{:error,  
%K8s.Client.HTTPError{message: {:tls_alert, {:handshake_failure, 
'TLS client: In state wait_cert at ssl_handshake.erl:2100 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}}, 
adapter_specific_error: %Mint.TransportError{reason: {:tls_alert, {:handshake_failure, 'TLS client: In state wait_cert at ssl_handshake.erl:2100 generated CLIENT ALERT: Fatal - Handshake Failure\n {bad_cert,hostname_check_failed}'}
}}}
```

Checking the local kube instance via curl the subject is set to: "subject: CN=kube-apiserver" which won't match for a localhost IP. So we need someway to disable that checking. From looking at the mint code currently https://github.com/elixir-mint/mint/blob/56c1734ea946a387377deeceaead33a900c4041e/lib/mint/core/transport/ssl.ex#L466

There doesn't seem to be a way to turn off hostname verification while leaving on SSL cert verification.

**Comment by mruoss** [comment]
Thank @elliottneilclark  for testing the release candidate and resporting issues. I ran into the same issue and I can't figure out why that worked with HTTPoison. 

This being said, there is a way to turn off hostname verification on the `K8s.Conn` struct. The API for it is not very nice but you can set the flag like this:

```elixir
{:ok, conn} = K8s.Conn.from_file(...)
conn = struct!(conn, insecure_skip_tls_verify: true)
```

**Comment by mruoss** [comment]
added a note to the [migration guide](https://hexdocs.pm/k8s/2.0.0-rc.2/migrations.html#local-clusters-and-tls-hostname-verification).

**Comment by mruoss** [comment]
I hope this resolves it for you @elliottneilclark. Closing it now.

**Comment by mruoss** [comment]
@elliottneilclark https://github.com/erlang/otp/issues/7968

**Comment by elliottneilclark** [comment]
Thank you, @mruoss. That is some nice debugging.

**Comment by mruoss** [comment]
Note that you can remove your `insecure_skip_tls_verify: true` with version 2.6.1.
