### ISSUE TITLE
Configuration of http_provider and discovery_driver is ignored

### ISSUE THREAD

**Issue by quexpl** [coryodaniel/k8s#217]
I have a problem with the configuration of default `:http_provider`, `:discovery_driver` and `:discovery_opts`.  I'm using k8s 1.2.0. In my `config/test.exs` I have:
```elixr
config :k8s,
  http_provider: Kubex.K8sMock,
  discovery_driver: K8s.Discovery.Driver.File,
  discovery_opts: [config: "test/fixtures/k8s_discovery.json"]
```

but seems like it ignores my config:
```
iex(1)> Application.get_env(:kubex, :env)
:test
iex(2)> %K8s.Conn{}
%K8s.Conn{
  cluster_name: nil,
  user_name: nil,
  url: "",
  insecure_skip_tls_verify: false,
  ca_cert: nil,
  auth: nil,
  middleware: %K8s.Middleware.Stack{
    request: [K8s.Middleware.Request.Initialize,
     K8s.Middleware.Request.EncodeBody],
    response: []
  },
  discovery_driver: K8s.Discovery.Driver.HTTP,
  discovery_opts: [],
  http_provider: K8s.Client.HTTPProvider,
  cacertfile: "/app/_build/test/lib/castore/priv/cacerts.pem"
}
iex(3)> K8s.default_http_provider() 
Kubex.K8sMock
```

As a workaround I'm able to initialize `%K8s.Conn{}` with proper values.
```
%K8s.Conn{
         http_provider: Kubex.K8sMock,
         discovery_driver: K8s.Discovery.Driver.File,
         discovery_opts: [config: "test/fixtures/k8s_discovery.json"]
       }
```

I don't quite understand why `%K8s.Conn{}` doesn't use the default value from `K8s.default_http_provider()`?

**Comment by mruoss** [comment]
are you importing `config/test.exs` in `config/config.exs`?

```elixir
# config/config.exs

import_config "#{config_env()}.exs"
```

**Comment by mruoss** [comment]
Actually... Not sure this is supposed work! Have you read somewhere that you can define these values in config?

**Comment by mruoss** [comment]
Oh yeah it should work - the relevant code is in`k8s.ex`. so... back to "are you importing test.exs?"

**Comment by quexpl** [comment]
Yes I'm, as you can see in the iex example, I'm running it with `MIX_ENV=test`, and `K8s.default_http_provider()` returns value from the `config/test.exs` but when I'm initializing struct `%K8s.Conn{}` it ignores the settings.

**Comment by mruoss** [comment]
No I can't see it in your example. Please paste the content of `config/config.exs` (not `config/test.exs`)

**Comment by quexpl** [comment]
It's described under the [testing in the docs](https://hexdocs.pm/k8s/testing.html).
Yes I'm loading the env config file in the config.exs. I'm working on a webapp with phoenix.

# config/config.exs
```
# This file is responsible for configuring your application
# and its dependencies with the aid of the Config module.
#
# This configuration file is loaded before any dependency and
# is restricted to this project.

# General application configuration
import Config

config :kubex, :env, Mix.env()

... REDACTED ...

# Import environment specific config. This must remain at the bottom
# of this file so it overrides the configuration defined above.
import_config "#{config_env()}.exs"
```

As you can see here, when I'm running an interactive elixir shell with test env, I can confirm that `K8s.default_http_provider() ` is working fine and uses value from config. But when I'm initializing the `K8s.Conn` struct it uses default value and ignores my config.

```
~> % MIX_ENV=test iex -S mix
Erlang/OTP 25 [erts-13.1] [source] [64-bit] [smp:16:16] [ds:16:16:10] [async-threads:1] [jit:ns]

Generated kubex app
Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Application.get_env(:kubex, :env)
:test
iex(2)> K8s.default_http_provider() 
Kubex.K8sMock
iex(3)> %K8s.Conn{} 
%K8s.Conn{
  cluster_name: nil,
  user_name: nil,
  url: "",
  insecure_skip_tls_verify: false,
  ca_cert: nil,
  auth: nil,
  middleware: %K8s.Middleware.Stack{
    request: [K8s.Middleware.Request.Initialize,
     K8s.Middleware.Request.EncodeBody],
    response: []
  },
  discovery_driver: K8s.Discovery.Driver.HTTP,
  discovery_opts: [],
  http_provider: K8s.Client.HTTPProvider,
  cacertfile: "/app/_build/test/lib/castore/priv/cacerts.pem"
}
```

**Comment by mruoss** [comment]
Okay I see now. Use the functions provided by the `K8s.Conn` module to initialize the connection. E.g. `K8s.Conn.from_file/2` or `K8s.Conn.from_service_account/N`. That's also how it is initialized on the test docs.

https://hexdocs.pm/k8s/1.2.0/K8s.Conn.html

**Comment by quexpl** [comment]
Yes I'm using the `K8s.Conn.from_file/2` and it works fine - but for testing I don't have the same clusters. According to the [testing docs](https://hexdocs.pm/k8s/testing.html) it should allow me to override the `http_provider`, `discovery_driver` and `discovery_opts` but it does not work. Maybe I didn't communicate it clearly before, but the problem is in the configuration for the test environment.

**Comment by mruoss** [comment]
Sorry, it might have been me being unclear: The configuration for the test environment is only read when using either of the two functions `K8s.Conn.from_file/2` or `K8s.Conn.from_service_account/N`. When just creating `%K8s.Conn{}` the default values of `defstruct` are used and config is not read at the moment.

**Comment by quexpl** [comment]
In the `K8s.Conn`  module the `defstruct` uses default values with functions which should read my config. 

k8s/conn.ex:
```elixir
  defstruct cluster_name: nil,
            user_name: nil,
            url: "",
            insecure_skip_tls_verify: false,
            ca_cert: nil,
            auth: nil,
            middleware: K8s.Middleware.Stack.default(),
            discovery_driver: K8s.default_discovery_driver(),
            discovery_opts: K8s.default_discovery_opts(),
            http_provider: K8s.default_http_provider(),
            cacertfile: K8s.default_cacertfile()
```

k8s.ex:
```elixir
  def default_http_provider do
    Application.get_env(:k8s, :http_provider, K8s.Client.MintHTTPProvider)
  end

  def default_discovery_driver do
    Application.get_env(:k8s, :discovery_driver, K8s.Discovery.Driver.HTTP)
  end

  def default_discovery_opts do
    Application.get_env(:k8s, :discovery_opts, [])
  end
```

For me it looks like defstruct is being defined before `Application.get_env(:k8s, :http_provider)` can read the value from the config and it uses default value instead. But when I'm running `K8s.default_http_provider()` it returns expected value.

**Comment by mruoss** [comment]
Oooh, my fault. You are right, it's there in the defstruct defaults! Sorry!

I have tested this and it works as expected for me:

```elixir
# config/test.exs

import Config

config :k8s,
  discovery_driver: K8s.Discovery.Driver.File,
  discovery_opts: [config: "test/support/discovery/example.json"],
  http_provider: K8s.Client.DynamicHTTPProvider,
  cacertfile: "/etc/ssl/cert.pem",
  websocket_provider: K8s.Client.DynamicWebSocketProvider
```

```
➜ iex -S mix
Erlang/OTP 25 [erts-13.1.3] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> %K8s.Conn{}
%K8s.Conn{
  cluster_name: nil,
  user_name: nil,
  url: "",
  insecure_skip_tls_verify: false,
  ca_cert: nil,
  auth: nil,
  middleware: %K8s.Middleware.Stack{
    request: [K8s.Middleware.Request.Initialize,
     K8s.Middleware.Request.EncodeBody],
    response: []
  },
  discovery_driver: K8s.Discovery.Driver.File,
  discovery_opts: [config: "test/support/discovery/example.json"],
  http_provider: K8s.Client.DynamicHTTPProvider,
  cacertfile: "/etc/ssl/cert.pem"
}
```

Same version of Elixir, so... where's the difference...?

**Comment by mruoss** [comment]
Maybe try `mix clean`?

**Comment by quexpl** [comment]
Thanks! Now it works :)
