### ISSUE TITLE
what is different between k8s lib and swarm ?

### ISSUE THREAD

**Issue by chanphiromsok** [coryodaniel/k8s#253]
I see ```swarm``` https://github.com/bitwalker/swarm  elixir library it used with Kubernetes so what is different between these two or does it just have the same purpose?

**Comment by royveshovda** [comment]
Let me try to explain my understanding of the difference. 

Kubernetes have a quite rich API to operate (and configure) loads. Everything from hosts down to the smallest container inside a pod can be examined and changed using the API. K8S library makes using the API (which is originally REST based) much simpler from Elixir code.

Swarm on the other hand, also talks to this same API, but the purpose of swarm is not the API itself, but rather to run distributed Elixir/Erlang nodes on top of kubernetes. So, Swarm (and libcluster) uses Kubernetes API (and could probably benefit from using K8S) to coordinated distributed Elixir/Erlang on top of Kubernetes.

Does this make sense?

**Comment by chanphiromsok** [comment]
thanks for explain I will research more about these 2
