### ISSUE TITLE
Hex.pm Usage Guide doc is unavailable

### ISSUE THREAD

**Issue by thomascharbonnel** [coryodaniel/k8s#270]
Hi!

I've noticed some of the links in the README are dead now, eg. https://hexdocs.pm/k8s/usage.html
Are y'all aware of this issue?

**Comment by mruoss** [comment]
Credit Suisse uses Elixir for Infra? Nice! 😉

I was not aware of the failing links. Thanks for reporting it.

**Comment by thomascharbonnel** [comment]
Haha, this is for lowly me just now! Thanks for fixing the link!
