### ISSUE TITLE
Long-lasting shell connection example is broken

### ISSUE THREAD

**Issue by spacebat** [coryodaniel/k8s#299]
While so far I've been able to do everything I've tried with the k8s package (version 2.5.0), including connecting to pods/exec to run a shell script and waiting for command termination, the [example](https://hexdocs.pm/k8s/operations.html#opening-long-lasting-connections-e-g-a-shell-and-sending-messages-to-pods) right after that is broken.

Firstly the two `receive` calls are missing closing parentheses, but when I fix that the example hangs indefinitely because `:open` is never received. I've confirmed that nothing at all is received instead I check for any message with:

`receive do: (msg -> IO.inspect(msg, label: :msg); :ok), after: (10_000 -> IO.puts(:stderr, "Nothing received"))`

If I add `tty: true` to the operation setup, then I do receive `{:stdout, "$ "}` but that's it.

BTW I'm using k3s version v1.28.5+k3s1, and `kubectl exec -i` is working fine on that pod.

I can work around this by having a task that blocks waiting for the command to end rather than taking this async approach, but I wonder what's going wrong and if it's in the library how I might be able to help.

**Comment by mruoss** [comment]
Yes true, I have updated the docs. The `tty` option was missing and it's done a bit differently now. 
Please note you'd rather implement a `GenServer` or some kind of event loops to talk to a pod.

**Comment by spacebat** [comment]
Hey yeah that works. New observations:

- normally this works but occasionally the first thing received is "", then the second receive picks up the "$ " shell prompt
- consuming the rest of the messages, the echo of the terminal appears on stdout - even after I've sent "stty -echo\n" to suppress it

Nevertheless this is that huge transition from nothing to something I can work with. Thanks for the update!

**Comment by mruoss** [comment]
> the echo of the terminal appears on stdout

YES! That's it!! And it actually makes totally sense. Because on a real terminal (e.g `k8s_term`) you'd want to see what you type. So the terminal sends it right back at you. In `k8s_term` we send every key stroke to the pod. 

I will adapt the example again.

**Comment by mruoss** [comment]
Besides your points, there's also the fact that we don't know in how many chunks the Pod sends back the stdout messages.

I think the example is better now, wdyt?
