### ISSUE TITLE
Patch operations fail with a 415 error

### ISSUE THREAD

**Issue by Rodeoclash** [coryodaniel/k8s#32]
Patch operations to the K8s API require a slightly different header from other operations, that is: `Content-Type: application/merge-patch+json`

Unless that header is present, the request will fail with: `415: Unsupported Media Type`

Further details can be found in: https://github.com/kubernetes/kubernetes/issues/61103

Looks like this fix would be located in: https://github.com/coryodaniel/k8s/blob/master/lib/k8s/client/http_provider.ex#L90 unless I'm misunderstanding something about the HTTP client. I can pick this one up shortly.

**Comment by coryodaniel** [comment]
The hard coded headers could probably be moved to K8s.Operation in a map like verbs/methods.

**Comment by coryodaniel** [comment]
@Rodeoclash mind giving that a whirl?

**Comment by Rodeoclash** [comment]
@coryodaniel Hey, looks like you beat me to it! Just pulled master and it's working a charm :+1:

**Comment by coryodaniel** [comment]
Woot. Hoping to cut 0.3 this weekend sometime. I’ll ping when I do. 

Thanks,

Cory O’Daniel
