### ISSUE TITLE
Handle text/plain HTTP responses

### ISSUE THREAD

**Issue by coryodaniel** [coryodaniel/k8s#38]
See [comment](https://github.com/coryodaniel/k8s/issues/29#issuecomment-521228581).

All responses are JSON decoded, add `Content-Type` check to return plain text.

https://github.com/coryodaniel/k8s/pull/37

@Rodeoclash

**Comment by Rodeoclash** [comment]
You're too fast at adding the fixes, give me a chance to submit a PR! 😀 

I think returning the entire blob is fine, push the implementation on how to handle it upstream to the consumer of the library. Otherwise I think the PR looks great.
