### ISSUE TITLE
Service Discovery Timeout

### ISSUE THREAD

**Issue by Rodeoclash** [coryodaniel/k8s#45]
This might fall under the umbrella of https://github.com/coryodaniel/k8s/issues/43

I'm also unsure how this could actually be _fixed_ but figured I'd raise it any way and we can close the ticket if it's a problem we have to live with.

The gist of it is: https://sentry.io/share/issue/1d3b7deedd2d41c4bc9eb0b533c0fcc7/

The context is that the provider I'm using for Kubernetes (Digital Ocean) will timeout on random requests, I guess due to network conditions. These timeouts are transient (and not just related to service discovery but every interaction with the API). One possible solution is to mitigate with an automatic retry (https://hexdocs.pm/httpoison_retry/HTTPoison.Retry.html).

**Comment by coryodaniel** [comment]
Ive been itching to address the discovery portion of this library. Just haven't had the time to get to it in the past few weeks. I think this ticket is valid and I think using autoretry in the JIT Discovery is a great idea.

Related: #43 #44

**Comment by coryodaniel** [comment]
Recapping on this as I'm starting the refactoring of Discovery this weekend.

* [ ] Add option to `k8s` config for max retries for Discovery requests
* [ ] Add option to `run/N` for setting max retries for a resource request
* [ ] Consider custom retry impl to allow for jitter on retry v. fixed wait (as below)

**Config example:**
```elixir
config :k8s, clusters: %{
  default: %{
    discovery_retries: N
  } 
}
```

**HTTPoison retry example:**

```elixir
HTTPoison.get("https://www.example.com")
|> autoretry(max_attempts: 5, wait: 15000, include_404s: false, retry_unknown_errors: false)
```

**Comment by Rodeoclash** [comment]
That seems very reasonable. Retries for individual requests via `run` may already be accessible via the options pass-thru to HTTPoison (if I'm remembering correctly!)

Weirdly enough, I haven't seen this error occur for quite some time. Perhaps DO have mitigated whatever the issue was that caused the problem in the first place.
