### ISSUE TITLE
Support kube `exec` auth

### ISSUE THREAD

**Issue by coryodaniel** [coryodaniel/k8s#5]
Add support for [`exec` auth](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuration)

**Comment by bforchhammer** [comment]
Hey, thanks your work on the k8s library!

For what it's worth, I've drafted an implementation for exec auth: https://gist.github.com/bforchhammer/b2a22caef43e7426e041f94a6655b552

It's not a complete implementation, but works with the `aws-iam-authenticator` and an EKS cluster :)

**Comment by coryodaniel** [comment]
Nice! How was working with the behavior and protocol for adding auth?

You should submit it as a PR it’s better to have support some support for it!

Thanks,

Cory O’Daniel
