### ISSUE TITLE
Watch times out after 5 seconds

### ISSUE THREAD

**Issue by jadencodes** [coryodaniel/k8s#62]
I spawn a genserver to listen for pod create/delete events like this:
```elixir
  @impl true
  def init(stack) do
    operation = K8s.Client.list("v1", :pod, namespace: "default")
    {:ok, ref} = K8s.Client.Runner.Watch.run(operation, :default, 0, stream_to: self())
    Logger.info "Starting watcher with ref #{inspect(ref)}"
    {:ok, stack}
  end

  @impl true
  def handle_info(val, state) do
    Logger.debug "Got info: #{inspect(val)}"
    {:noreply, state}
  end
```

It works great for the first 5 seconds, but then throws this: 
```14:40:36.664 [debug] Got info: %HTTPoison.Error{id: #Reference<0.593330850.2224553994.255733>, reason: {:closed, :timeout}}```

I'm not sure if I'm using the watch functionality incorrectly, or if this is a bug. I have run it both internally and externally with the same issue.

I went down this path as well as creating a controller for the pods and pattern matching on the pods I want. I'm not sure if either way is correct/better but if you had any suggestions I am very open!

Thanks.

**Comment by coryodaniel** [comment]
You should be able to set the timeout. This is how I do it in [bonny](https://github.com/coryodaniel/bonny/blob/master/lib/bonny/server/watcher.ex#L163)

**Comment by coryodaniel** [comment]
Let me know if this persists!

**Comment by jadencodes** [comment]
Ah thank you! Is there a problem with setting it to infinity? I think I'm missing what the use case would be for setting a shortish watch unless it was attempting to do what `wait` is doing.

**Comment by jadencodes** [comment]
FWIW I am using Bonny but a bit confused on where to use the Bonny lib vs this one. I would like to just watch the pods of my deployment (I need the cluster IP's of them when they go down/up) so perhaps using a controller on the Pod resource is better?

**Comment by coryodaniel** [comment]
Im not sure what HTTPoison will do if its set to infinity, but that would try to keep an HTTP long polling request open forever, so it could get flakey.

Bonny is (currently) for creating operators... you can abuse it to get a better watcher though. You have three options:

1. You could use bonny and make an operator and set the controller to look for pods, you would just need to remove the CRD stuff from the manifest.yaml that it creates.
2. `use Bonny.Server.Watcher` this macro is what drives the operator's controller. The tests and examples even give [an example](https://github.com/coryodaniel/bonny/blob/master/lib/bonny/server/watcher.ex#L16) with pods. The macro adds a start_link function that can be used with your supervision tree.
3.  Back the code out of [watcher.ex](https://github.com/coryodaniel/bonny/blob/master/lib/bonny/server/watcher.ex#L16) into your app and just use `k8s`. 

I think 2 is your better option. One note with option 2 is it [may break in 1.0](https://github.com/coryodaniel/bonny/issues/82) (not anytime soon), but I plan to make using the internal pieces of bonny a little easier so its not _solely_ about operators.

**Comment by coryodaniel** [comment]
There is an example of monitoring deployments [here](https://github.com/coryodaniel/bonny/blob/master/examples/deployment_event_log_controller.ex). I still suggest option 2 above.

**Comment by jadencodes** [comment]
@coryodaniel thank you for the options! I had sort of stumbled into option 2 but was having problems and started going down option 1. I will look back into it today because that is what you recommend. Thanks for all your help! I may open a PR with some examples for watcher if I get it working sufficiently.

**Comment by alexgleason** [comment]
I'm really struggling to make it work with K8s.Client.run:

```elixir
iex(9)> r |> K8s.Client.get() |> K8s.Client.run(conn)
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
iex(10)> r |> K8s.Client.get() |> K8s.Client.run(conn, recv_timeout: :infinity)
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
iex(11)> r |> K8s.Client.get() |> K8s.Client.run(conn, recv_timeout: 9999999999999)
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
iex(12)> r |> K8s.Client.get() |> K8s.Client.run(conn, timeout: :infinity, recv_timeout: :infinity)
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
iex(13)> 
```

It keeps lasting 5 seconds.

**Comment by coryodaniel** [comment]
Is this for a watch request?

**Comment by alexgleason** [comment]
No it's just a regular run command, but I commented here cuz it seemed related.

**Comment by coryodaniel** [comment]
Can you open a new issue w/ k8s.ex version info and kubernetes version info?

Also, maybe runnable example using a basic nginx pod and the request you’re running. 

I’ll have some time this weekend I can look over it.

Thanks,

Cory O’Daniel
