### ISSUE TITLE
`%Operation{}` should include query params

### ISSUE THREAD

**Issue by jwietelmann** [coryodaniel/k8s#66]
It seems to me that it is strange for the struct to encapsulate body data but not query params. Not sure if you have a reason for doing what you're currently doing, but I would think it would make more sense for `%Operation{}` to be a complete specification of the request that you're about to make.

My app (that I'm trying to port to use `k8s`) uses Dex to get tokens via oauth2. Consider the case where my token expires. If the operation struct encapsulates everything including query params, I can make the user re-authenticate, and then I can replay the operation as is. If the operation doesn't encapsulate the query params, I have to fold it into another data structure that does.

**Comment by coryodaniel** [comment]
Only because I haven’t needed params yet in my own apps. I’ll add this to the 0.5.1 milestone. 

A bit backed up w the apocalypse...
