### ISSUE TITLE
Nitpick: Shouldn't the `conn` argument come first, for every function that uses it?

### ISSUE THREAD

**Issue by jwietelmann** [coryodaniel/k8s#67]
Stylistically, I think the API might flow/read better if you could write this:

```
cluster_name
|> get_unauthenticated_conn()
|> set_auth_token(my_auth_token)
|> Client.run(operation)
```

**Comment by coryodaniel** [comment]
I bikeshedded in this. It’s a leftover from having a ‘:default’ cluster so you didn’t have to specify the name.

I’ll see if I can play w pattern matching to get this into 0.5.1 w backwards compatibility for how it currently works

**Comment by coryodaniel** [comment]
This was getting dark, going to target 1.0 which I plan to start to work on after this last issue in [0.5.1](https://github.com/coryodaniel/k8s/milestone/3)

**Comment by coryodaniel** [comment]
@mruoss What are your thoughts on this? Trying to get the 1.0 out this week!

**Comment by mruoss** [comment]
Hmm... I've been using k8s and bonny with a single (:default) connection and it felt right to pipe operations into Client.run(:default). While I see this being handy in other use cases, I never missed the API with cluster/conn being the first argument. It might be possible to support both version by fiddling with pattern matching - but you'd have to maintain both, so...

**Comment by mruoss** [comment]
> Trying to get the 1.0 out this week!

Excited to hear!

**Comment by coryodaniel** [comment]
Yeah I tried to make it backwards compatible and support both but it was getting pretty messy.

Ah you are still using `:default`, what version are you on?

**Comment by mruoss** [comment]
Well, [ask bonny](https://github.com/coryodaniel/bonny/blob/master/mix.exs)! ;)
