### ISSUE TITLE
Example of access/read configmaps

### ISSUE THREAD

**Issue by sleipnir** [coryodaniel/k8s#94]
Is it possible to read the settings of a configmap? If so, is there an example? If not, would it be possible to add this feature?

**Comment by sleipnir** [comment]
Hello friends! Any comment about it?

**Comment by coryodaniel** [comment]
Yes, all resource types are supported.

[Listing a resource](https://github.com/coryodaniel/k8s/blob/develop/guides/operations.md#listing-deployments)

[Getting a resource](https://github.com/coryodaniel/k8s/blob/develop/guides/operations.md#getting-a-deployment)

Replace the deployment api/kind w/ ConfigMap.

**Comment by sleipnir** [comment]
Thanks @coryodaniel
