### ISSUE TITLE
Better observability

### ISSUE THREAD

**Issue by coryodaniel** [coryodaniel/k8s#95]
* [x] remove notion, replace telemetry
* [x] add open telemetry API for tracing
* [x] structured logs + a `library: :k8s` so users can filter logs

**Comment by mruoss** [comment]
> remove notion, replace with telemetry

absolutely!

> add open telemetry API for tracing

YES! But maybe as a separate module? Some might want opentelemetry, others spandex,...

> structured logs + a library: :k8s so users can filter logs

I think log formatting is up to the application, not the library. But adding default metadata for sure.

**Comment by mruoss** [comment]
> YES! But maybe as a separate module? Some might want opentelemetry, others spandex,...

Or optional dependency...
